program FmxAdvancedTestApp;

uses
  System.StartUpCopy,
  FMX.Forms,
  uMain in 'uMain.pas' {FormMain},
  ZXing.OneD.UPCEANReader in '..\lib\Classes\1D Barcodes\ZXing.OneD.UPCEANReader.pas',
  ZXing.OneD.UPCEANExtensionSupport in '..\lib\Classes\1D Barcodes\ZXing.OneD.UPCEANExtensionSupport.pas',
  ZXing.OneD.UPCEANExtension5Support in '..\lib\Classes\1D Barcodes\ZXing.OneD.UPCEANExtension5Support.pas',
  ZXing.OneD.UPCEANExtension2Support in '..\lib\Classes\1D Barcodes\ZXing.OneD.UPCEANExtension2Support.pas',
  ZXing.OneD.OneDReader in '..\lib\Classes\1D Barcodes\ZXing.OneD.OneDReader.pas',
  ZXing.OneD.ITFReader in '..\lib\Classes\1D Barcodes\ZXing.OneD.ITFReader.pas',
  ZXing.OneD.EANManufacturerOrgSupport in '..\lib\Classes\1D Barcodes\ZXing.OneD.EANManufacturerOrgSupport.pas',
  ZXing.OneD.EAN8Reader in '..\Lib\Classes\1D Barcodes\ZXing.OneD.EAN8Reader.pas',
  ZXing.OneD.EAN13Reader in '..\lib\Classes\1D Barcodes\ZXing.OneD.EAN13Reader.pas',
  ZXing.OneD.Code93Reader in '..\lib\Classes\1D Barcodes\ZXing.OneD.Code93Reader.pas',
  ZXing.OneD.Code128Reader in '..\lib\Classes\1D Barcodes\ZXing.OneD.Code128Reader.pas',
  ZXing.QrCode.QRCodeReader in '..\lib\Classes\2D Barcodes\ZXing.QrCode.QRCodeReader.pas',
  ZXing.Datamatrix.DataMatrixReader in '..\lib\Classes\2D Barcodes\ZXing.Datamatrix.DataMatrixReader.pas',
  ZXing.QrCode.Internal.Version in '..\lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.Version.pas',
  ZXing.QrCode.Internal.QRCodeDecoderMetaData in '..\lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.QRCodeDecoderMetaData.pas',
  ZXing.QrCode.Internal.Mode in '..\lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.Mode.pas',
  ZXing.QrCode.Internal.FormatInformation in '..\lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.FormatInformation.pas',
  ZXing.QrCode.Internal.ErrorCorrectionLevel in '..\lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.ErrorCorrectionLevel.pas',
  ZXing.QrCode.Internal.Decoder in '..\lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.Decoder.pas',
  ZXing.QrCode.Internal.DecodedBitStreamParser in '..\lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.DecodedBitStreamParser.pas',
  ZXing.QrCode.Internal.DataMask in '..\lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.DataMask.pas',
  ZXing.QrCode.Internal.DataBlock in '..\lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.DataBlock.pas',
  ZXing.QrCode.Internal.BitMatrixParser in '..\lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.BitMatrixParser.pas',
  ZXing.Datamatrix.Internal.Version in '..\lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.Version.pas',
  ZXing.Datamatrix.Internal.Decoder in '..\lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.Decoder.pas',
  ZXing.Datamatrix.Internal.DecodedBitStreamParser in '..\lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.DecodedBitStreamParser.pas',
  ZXing.Datamatrix.Internal.DataBlock in '..\lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.DataBlock.pas',
  ZXing.Datamatrix.Internal.BitMatrixParser in '..\lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.BitMatrixParser.pas',
  ZXing.QrCode.Internal.FinderPatternInfo in '..\lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPatternInfo.pas',
  ZXing.QrCode.Internal.FinderPatternImplementation in '..\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPatternImplementation.pas',
  ZXing.QrCode.Internal.FinderPatternFinder in '..\lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPatternFinder.pas',
  ZXing.QrCode.Internal.FinderPattern in '..\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPattern.pas',
  ZXing.QrCode.Internal.Detector in '..\lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.Detector.pas',
  ZXing.QrCode.Internal.AlignmentPatternImplementation in '..\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.AlignmentPatternImplementation.pas',
  ZXing.QrCode.Internal.AlignmentPatternFinder in '..\lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.AlignmentPatternFinder.pas',
  ZXing.QrCode.Internal.AlignmentPattern in '..\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.AlignmentPattern.pas',
  ZXing.Datamatrix.Internal.Detector in '..\lib\Classes\2D Barcodes\Detector\ZXing.Datamatrix.Internal.Detector.pas',
  ZXing.StringUtils in '..\lib\Classes\Common\ZXing.StringUtils.pas',
  ZXing.ResultPointImplementation in '..\Lib\Classes\Common\ZXing.ResultPointImplementation.pas',
  ZXing.ResultPoint in '..\lib\Classes\Common\ZXing.ResultPoint.pas',
  ZXing.ResultMetadataType in '..\lib\Classes\Common\ZXing.ResultMetadataType.pas',
  ZXing.ReadResult in '..\lib\Classes\Common\ZXing.ReadResult.pas',
  ZXing.Reader in '..\lib\Classes\Common\ZXing.Reader.pas',
  ZXing.MultiFormatReader in '..\lib\Classes\Common\ZXing.MultiFormatReader.pas',
  ZXing.Helpers in '..\lib\Classes\Common\ZXing.Helpers.pas',
  ZXing.EncodeHintType in '..\lib\Classes\Common\ZXing.EncodeHintType.pas',
  ZXing.DefaultGridSampler in '..\lib\Classes\Common\ZXing.DefaultGridSampler.pas',
  ZXing.DecoderResult in '..\lib\Classes\Common\ZXing.DecoderResult.pas',
  ZXing.DecodeHintType in '..\lib\Classes\Common\ZXing.DecodeHintType.pas',
  ZXing.Common.PerspectiveTransform in '..\lib\Classes\Common\ZXing.Common.PerspectiveTransform.pas',
  ZXing.Common.GridSampler in '..\lib\Classes\Common\ZXing.Common.GridSampler.pas',
  ZXing.Common.DetectorResult in '..\lib\Classes\Common\ZXing.Common.DetectorResult.pas',
  ZXing.Common.BitMatrix in '..\lib\Classes\Common\ZXing.Common.BitMatrix.pas',
  ZXing.Common.BitArrayImplementation in '..\Lib\Classes\Common\ZXing.Common.BitArrayImplementation.pas',
  ZXing.Common.BitArray in '..\lib\Classes\Common\ZXing.Common.BitArray.pas',
  ZXing.CharacterSetECI in '..\lib\Classes\Common\ZXing.CharacterSetECI.pas',
  ZXIng.ByteSegments in '..\Lib\Classes\Common\ZXIng.ByteSegments.pas',
  ZXing.BitSource in '..\lib\Classes\Common\ZXing.BitSource.pas',
  ZXing.BarcodeFormat in '..\lib\Classes\Common\ZXing.BarcodeFormat.pas',
  ZXing.ScanManager in '..\lib\Classes\ZXing.ScanManager.pas',
  ZXing.RGBLuminanceSource in '..\lib\Classes\Filtering\ZXing.RGBLuminanceSource.pas',
  ZXing.PlanarYUVLuminanceSource in '..\lib\Classes\Filtering\ZXing.PlanarYUVLuminanceSource.pas',
  ZXing.LuminanceSource in '..\lib\Classes\Filtering\ZXing.LuminanceSource.pas',
  ZXing.InvertedLuminanceSource in '..\lib\Classes\Filtering\ZXing.InvertedLuminanceSource.pas',
  ZXing.HybridBinarizer in '..\lib\Classes\Filtering\ZXing.HybridBinarizer.pas',
  ZXing.GlobalHistogramBinarizer in '..\lib\Classes\Filtering\ZXing.GlobalHistogramBinarizer.pas',
  ZXing.BinaryBitmap in '..\lib\Classes\Filtering\ZXing.BinaryBitmap.pas',
  ZXing.Binarizer in '..\lib\Classes\Filtering\ZXing.Binarizer.pas',
  ZXing.BaseLuminanceSource in '..\lib\Classes\Filtering\ZXing.BaseLuminanceSource.pas',
  ZXing.Common.Detector.WhiteRectangleDetector in '..\lib\Classes\Common\Detector\ZXing.Common.Detector.WhiteRectangleDetector.pas',
  ZXing.Common.Detector.MathUtils in '..\lib\Classes\Common\Detector\ZXing.Common.Detector.MathUtils.pas',
  ZXing.Common.ReedSolomon.ReedSolomonDecoder in '..\lib\Classes\Common\ReedSolomon\ZXing.Common.ReedSolomon.ReedSolomonDecoder.pas',
  ZXing.Common.ReedSolomon.GenericGF in '..\lib\Classes\Common\ReedSolomon\ZXing.Common.ReedSolomon.GenericGF.pas',
  ZXing.OneD.UPCAReader in '..\Lib\Classes\1D Barcodes\ZXing.OneD.UPCAReader.pas',
  ZXing.OneD.Code39Reader in '..\Lib\Classes\1D Barcodes\ZXing.OneD.Code39Reader.pas',
  ZXing.OneD.UPCEReader in '..\Lib\Classes\1D Barcodes\ZXing.OneD.UPCEReader.pas',
  AudioManager in 'AudioManager\AudioManager.pas' {$R *.res};

{$R *.res}
{$ASSERTIONS OFF}

begin
  Application.Initialize;
  Application.CreateForm(TFormMain, FormMain);
  Application.Run;
end.
